Complete separate boss.test.config & rebar_plugin basic versioning
All the boss.config initialization now happens on boss_plugin, this
lets us have a complete (including boss path installation) for the
testing environment.

As this change needs the plugin to be copied again, I implemented
a really simple version detection system, if you don't have the
latests required plugin from skel, the system instructs you to
recopy:

ERROR: Your boss_rebar plugin is outdated, please copy it again from
your updated ChicagoBoss installation:
Guessed command:
cp ../cb_core/skel/priv/rebar/boss_plugin.erl priv/rebar/boss_plugin.erl