Update rebar.config
latest version don't compile, on my machine:
seem i need to change order of deps to make it compile, put lager and erlando before other.

/home/mihawk/vagrant/ChicagoBoss/deps/cowlib/src/cow_http.erl:none: undefined parse transform 'lager_transform'
ERROR: compile failed while processing /home/mihawk/vagrant/ChicagoBoss/deps/cowlib: rebar_abort
make: *** [all] Error 1